export const toWallet = () => ({ type: 'WALLET' })
export const toCreate = () => ({ type: 'CREATE' })
export const toImport = () => ({ type: 'IMPORT' })
export const toInit = () => ({ type: 'INIT' })
export const toLock = () => ({ type: 'LOCK' })
