export const FETCH_ADDRESS_FAILURE = 'FETCH_ADDRESS_FAILURE'
export const FETCH_ADDRESS_REQUEST = 'FETCH_ADDRESS_REQUEST'
export const FETCH_ADDRESS_SUCCESS = 'FETCH_ADDRESS_SUCCESS'

export const CREATE_ADDRESS_FAILURE = 'CREATE_ADDRESS_FAILURE'
export const CREATE_ADDRESS_REQUEST = 'CREATE_ADDRESS_REQUEST'
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS'

export const CREATE_MNEMONIC_FAILURE = 'CREATE_MNEMONIC_FAILURE'
export const CREATE_MNEMONIC_REQUEST = 'CREATE_MNEMONIC_REQUEST'
export const CREATE_MNEMONIC_SUCCESS = 'CREATE_MNEMONIC_SUCCESS'

export const CREATE_SEED_SUCCESS = 'CREATE_SEED_SUCCESS'
export const CREATE_SEED_REQUEST = 'CREATE_SEED_REQUEST'
export const ADD_SEED_POINT = 'ADD_SEED_POINT'
