export const FETCH_ALL_KEYS_FAILURE = 'FETCH_ALL_KEYS_FAILURE'
export const FETCH_ALL_KEYS_SUCCESS = 'FETCH_ALL_KEYS_SUCCESS'

export const CREATE_KEY_FAILURE = 'CREATE_KEY_FAILURE'
export const CREATE_KEY_SUCCESS = 'CREATE_KEY_SUCCESS'

export const CREATE_MNEMONIC_FAILURE = 'CREATE_MNEMONIC_FAILURE'
export const CREATE_MNEMONIC_REQUEST = 'CREATE_MNEMONIC_REQUEST'
export const CREATE_MNEMONIC_SUCCESS = 'CREATE_MNEMONIC_SUCCESS'

export const CREATE_SEED_SUCCESS = 'CREATE_SEED_SUCCESS'
export const CREATE_SEED_REQUEST = 'CREATE_SEED_REQUEST'
export const ADD_SEED_POINT = 'ADD_SEED_POINT'

export const RESTORE_WALLET = 'RESTORE_WALLET'
export const SAVE_WALLET = 'SAVE_WALLET'
export const SAVE_WALLET_FAILURE = 'SAVE_WALLET_FAILURE'
export const FETCH_MASTER_PRIVATE_KEY = 'FETCH_MASTER_PRIVATE_KEY'

export const INCREASE_NOUNCE_DERIVATION = 'INCREASE_NOUNCE_DERIVATION'

export const MAKE_TRANSACTION_SUCCESS = 'MAKE_TRANSACTION_SUCCESS'
export const MAKE_TRANSACTION_FAILURE = 'MAKE_TRANSACTION_FAILURE'

export const FETCH_MNEMONIC = 'FETCH_MNEMONIC'
