export const FETCH_PRIVATE_KEYS_FAILURE = 'FETCH_PRIVATE_KEYS_FAILURE'
export const FETCH_PRIVATE_KEYS_REQUEST = 'FETCH_PRIVATE_KEYS_REQUEST'
export const FETCH_PRIVATE_KEYS_SUCCESS = 'FETCH_PRIVATE_KEYS_SUCCESS'

export const CREATE_PRIVATE_KEY_FAILURE = 'CREATE_PRIVATE_KEY_FAILURE'
export const CREATE_PRIVATE_KEY_REQUEST = 'CREATE_PRIVATE_KEY_REQUEST'
export const CREATE_PRIVATE_KEY_SUCCESS = 'CREATE_PRIVATE_KEY_SUCCESS'

export const CREATE_MNEMONIC_FAILURE = 'CREATE_MNEMONIC_FAILURE'
export const CREATE_MNEMONIC_REQUEST = 'CREATE_MNEMONIC_REQUEST'
export const CREATE_MNEMONIC_SUCCESS = 'CREATE_MNEMONIC_SUCCESS'

export const CREATE_SEED_SUCCESS = 'CREATE_SEED_SUCCESS'
export const CREATE_SEED_REQUEST = 'CREATE_SEED_REQUEST'
export const ADD_SEED_POINT = 'ADD_SEED_POINT'
